### ISSUE TITLE
Picasso 2.5.2 can not display sd pictures when use fit and resize method  in Android 5.1

### ISSUE THREAD

**Issue by tianshaokai** [square/picasso#1369] opened 2016-04-22 03:17 UTC
Picasso 2.5.2 can not display sd pictures when use fit and resize method  in Android 5.1. But it can display network or drawable image, Please help me solve this problem.

**Comment by JakeWharton** [comment] 2016-04-22 03:20
Dupe of #1368

**Closed by JakeWharton** 2016-04-22 03:20 UTC
