### ISSUE TITLE
How to save loaded image ,text into internal storage for offline loading ?

### ISSUE THREAD

**Issue by joy-sec** [square/picasso#1560] opened 2016-12-27 06:46 UTC
Hi,
I want to know 
How to save loaded image ,text into internal storage for offline load?

**Comment by JakeWharton** [comment] 2016-12-27 06:52
We currently don't have an API to save to a File. Dupe of #506. If you want offline your best bet is to use a normal HTTP client to download and save images and then use Picasso to load them from disk.

**Comment by joy-sec** [comment] 2016-12-27 06:53
then please share this method

**Closed by JakeWharton** 2016-12-27 06:52 UTC
