### ISSUE TITLE
java.io.IOException: Cannot reset

### ISSUE THREAD

**Issue by wenxiang20130910** [square/picasso#983] opened 2015-04-20 07:41 UTC
I have a problem when load a big image from local , and It's load error .
Picasso picasso = new Picasso.Builder(context).listener(new Picasso.Listener() {
            @Override public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
            }
        }).build();

        picasso
                .load("file://" + "/storage/sdcard0/20131103/DSC_0081.JPG")
                .fit()
                .centerCrop()
                .into((ImageView) findViewById(R.id.image));
--------------------------------

04-20 15:37:01.081  26923-26923/com.zivoo.life.app W/System.err﹕ java.io.IOException: Cannot reset
04-20 15:37:01.081  26923-26923/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
04-20 15:37:01.081  26923-26923/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
04-20 15:37:01.081  26923-26923/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
04-20 15:37:01.081  26923-26923/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
04-20 15:37:01.101  26923-26923/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
04-20 15:37:01.111  26923-26923/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-20 15:37:01.111  26923-26923/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-20 15:37:01.111  26923-26923/com.zivoo.life.app W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-20 15:37:01.111  26923-26923/com.zivoo.life.app W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
04-20 15:37:01.111  26923-26923/com.zivoo.life.app W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by JakeWharton** [comment] 2015-04-20 14:55
Dupe of https://github.com/square/picasso/issues/364

**Closed by JakeWharton** 2015-04-20 14:55 UTC

**Comment by wenxiang20130910** [comment] 2015-05-11 08:48
I can load this file from local sdcard . But I cannot load it from server when I push it to my server , and the error stack is the same with previous .
tip:this file size is 4608x3072 ;
