### ISSUE TITLE
Image not loading ==> Dispatcher batched [R3]+760ms for error, Main errored

### ISSUE THREAD

**Issue by boyfox** [square/picasso#1671] opened 2017-09-11 15:58 UTC
Hi all!
I have a following problem with loading image with Picasso:

![screen shot 2017-09-08 at 12 11 13 pm](https://user-images.githubusercontent.com/3168694/30200108-f7d50ed6-948e-11e7-810c-6d1eab7e321c.png)

this is image url: [normal image](http://booking.fussball-treff.com/media/2NZnPlbi4YBPheeYgnD0_1503924874_vmXTfLYe6xmRnri7WRz4.jpg)

this is large size of image: [large image](http://booking.fussball-treff.com/media/2NZnPlbi4YBPheeYgnD0_1503924874_vmXTfLYe6xmRnri7WRz4.jpg~large)

Just single instance in App and exception handler:

![screen shot 2017-09-09 at 10 48 00 am](https://user-images.githubusercontent.com/3168694/30237576-886e8a34-954e-11e7-8bfd-32fd883a388f.png)

This is exception:

![screen shot 2017-09-09 at 10 56 49 am](https://user-images.githubusercontent.com/3168694/30237594-eee2ec60-954e-11e7-86a3-8466aef4a0cc.png)

This is using in adapter:

![screen shot 2017-09-09 at 10 59 42 am](https://user-images.githubusercontent.com/3168694/30237597-fe50d7f2-954e-11e7-80e6-8528355202c8.png)

here sdk and dependency informations:

![screen shot 2017-09-09 at 10 57 49 am](https://user-images.githubusercontent.com/3168694/30237606-11a6396e-954f-11e7-93c1-9de7e9e3eec2.png)
![screen shot 2017-09-09 at 10 58 10 am](https://user-images.githubusercontent.com/3168694/30237608-11abc974-954f-11e7-815d-4543e04a36b9.png)
![screen shot 2017-09-09 at 10 58 19 am](https://user-images.githubusercontent.com/3168694/30237607-11ab8ab8-954f-11e7-861f-f8679438868a.png)

Device: Nexus 5, Android version 6.0.1

**Comment by JakeWharton** [comment] 2017-09-12 23:00
Dupe of #1670

**Closed by JakeWharton** 2017-09-12 23:00 UTC
