### ISSUE TITLE
Download multiple images and store in storage

### ISSUE THREAD

**Issue by FarshadKazemi** [square/picasso#827] opened 2015-01-03 17:17 UTC
I'm going to download images from the internet and save them in storage at the same time.
I know that I can save one image through calling Target class.
I use below code to download my images, but it just downloads one image.
Any suggestion would be appreciated ...

    @Override
     protected void onPostExecute(Void result) {
    SaveImages();
    pDialog.dismiss();
    super.onPostExecute(result);
    }
    }

    String fileName = null;
    public void SaveImages()
    {
    for(int i=0; i<image.length; i++)
    {
        Picasso.with(this).load(image[i]).into(target);
        fileName = "image-" + i + ".jpg";
    }
    }

    Target target = new Target() {

    @Override
    public void onPrepareLoad(Drawable arg0) {
        // TODO Auto-generated method stub

    }

    @Override
    public void onBitmapLoaded(Bitmap bitmap, LoadedFrom arg1) {

        File file = new File(Environment.getExternalStorageDirectory().getPath() +"/" + fileName);
         try 
         {
         file.createNewFile();
         FileOutputStream ostream = new FileOutputStream(file);
         bitmap.compress(CompressFormat.JPEG, 75, ostream);
         ostream.close();
         } 
         catch (Exception e) 
         {
         e.printStackTrace();
         }
    }

    @Override
    public void onBitmapFailed(Drawable arg0) {
        // TODO Auto-generated method stub

    }
    };

**Comment by JakeWharton** [comment] 2015-01-04 08:34
Dupe of #506.

**Closed by JakeWharton** 2015-01-04 08:34 UTC

**Comment by Baraka1Ahmad** [comment] 2018-02-04 07:17
Hello my friend
I encountered the same problem, you can make a Loop

**Comment by pnitish16** [comment] 2018-02-16 13:40
its loading single bitmap in all the files :(

**Comment by revdilip** [comment] 2018-07-25 11:38
@Barakahamad1 here you have named the file one and two, can we get the name there from url .
