### ISSUE TITLE
Sometime on network broken get half image

### ISSUE THREAD

**Issue by chwakil** [square/picasso#1789] opened 2018-03-07 12:29 UTC
Sometime on network broken I get half image with Picasso request and loading again Picasso return the same half image. After clearing cache of the application and downloading again url return correct image. Why not Picasso checks this automatically that is image content length same as server or not after downloading finish.

**Comment by JakeWharton** [comment] 2018-03-07 16:20
Dupe of #836. This is a bug in Android's bitmap decoding which incorrectly returns a bitmap without fully decoding and without throwing an exception. Sadly we have no control over this.

**Closed by JakeWharton** 2018-03-07 16:20 UTC

**Comment by Nomaan-Khan** [comment] 2018-04-26 12:00
Atleast Picasso can make sure if the full content is received , Android is decoding whatever it gets, User might want to display half image only.
