### ISSUE TITLE
BitmapHunter decodeStream fails as MarkableInputStream cannot be reset.

### ISSUE THREAD

**Issue by extorn** [square/picasso#2177] opened 2020-08-04 20:38 UTC
Picasso version 2.5.2
Java File:
`com.squareup.picasso.BitmapHunter`
line 117:
`long mark = markStream.savePosition(65536); // TODO fix this crap.`

The above line is causing a problem because the MarkableInputStream cannot be reset (line 140) since this 64Kb limit is exceeded for the files created by my device camera (a 3096 * 4128 pixel jpg image of size 3.4Mb).
This is happening for a local file referenced by a content Uri on android 10.
The result is that `markStream.reset(mark);` throws a `new IOException("Cannot reset");`

**Comment by JakeWharton** [comment] 2020-08-04 20:47
Dupe of #364. This is fixed on master in 3.0.0-SNAPSHOT, but there are no plans to release at this time unfortunately.

**Closed by JakeWharton** 2020-08-04 20:47 UTC
