### ISSUE TITLE
Large image loading fails (6000 X 4000 px)

### ISSUE THREAD

**Issue by csoni111** [square/picasso#1613] opened 2017-04-09 07:49 UTC
This [image](http://rickwright.co.nz/amahi/picture_library/this%20doesnt.JPG) does not seem to load using picasso.

**Image Properties:**
Type: JPG file
Dimensions: 6000 X 4000 pixels
Size: 12.2 MB

Error Log:
```
D/Picasso: Main        created      [R16] Request{url.. resize(100,100) centerCrop}
D/Picasso: Hunter      executing    [R16]+1ms 
D/Picasso: Dispatcher  enqueued     [R16]+1ms 
D/libc-netbsd: [getaddrinfo]: hostname=192.168.0.10; servname=(null); netid=0; mark=0
D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
I/System.out: [CDS]rx timeout:20000
I/System.out: [CDS]SO_SND_TIMEOUT:0
I/System.out: [OkHttp] sendRequest>>
I/System.out: [OkHttp] sendRequest<<
D/skia: jpeg_decoder mode 0, colorType 4, w 6000, h 4000, sample 1, bsLength 0!!
I/System.out: close [socket][/192.168.0.106:45679]
D/Picasso: Dispatcher  retrying     [R16]+738ms 
D/Picasso: Hunter      executing    [R16]+739ms 
D/libc-netbsd: [getaddrinfo]: hostname=192.168.0.10; servname=(null); netid=0; mark=0
D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
I/System.out: [CDS]rx timeout:20000
I/System.out: [CDS]SO_SND_TIMEOUT:0
I/System.out: [OkHttp] sendRequest>>
I/System.out: [OkHttp] sendRequest<<
D/skia: jpeg_decoder mode 0, colorType 4, w 6000, h 4000, sample 1, bsLength 0!!
I/System.out: close [socket][/192.168.0.106:55039]
I/System.out: [CDS]shutdownInput in read
I/System.out: close [socket][/:::55039]
I/System.out: close [socket][/:::55039]
D/Picasso: Dispatcher  retrying     [R16]+1398ms 
D/Picasso: Hunter      executing    [R16]+1399ms 
D/Picasso: Dispatcher  batched      [R16]+1403ms for error
D/Picasso: Dispatcher  delivered    [R16]+1609ms 
D/Picasso: Main        errored      [R16]+1614ms 
```

**Comment by Dragas** [comment] 2017-04-10 10:27
Are you sure it's not a `out of memory exception`?

**Comment by csoni111** [comment] 2017-04-10 11:20
yes I am sure, no OOM is thrown. Infact I have tried adding `android:largeHeap="true"` to the manifest but it does not help.
Also I am able to load the same image using other open source libraries like `Glide`, `UIL` etc.

**Comment by JakeWharton** [comment] 2017-04-12 01:20
Most Android devices have a max texture size in their GPUs of 2048x2048 or
4096x4096. I don't know of any that support larger than that, although they
probably exist on the phones with 4K displays. The Bitmap decoder will log
a message when this happens, but otherwise it silently fails. Do you
actually need to load the full size image? Are you using something like
`.fit().centerInside()`?

**Comment by csoni111** [comment] 2017-04-12 03:12
Yes we were using `.fit()` and `.centerInside()` both in the app for loading the images. [Here](https://github.com/amahi/android/blob/b6ff640854e605a701006b3d8fb79c8ece48d3f8/src/main/java/org/amahi/anywhere/fragment/ServerFileImageFragment.java#L77) is the code for reference.

**Comment by akshat62** [comment] 2017-05-29 06:36
https://developer.android.com/topic/performance/graphics/load-bitmap.html

**Comment by dunwen** [comment] 2017-06-13 09:56
i got the same problem .
when i use .fit().centerCrop() on a large image,it can not show. however,when i make the same image to 600*800 , this image is showed.how can i solve this problem? i use version 2.5.2

**Comment by talk2cerlin** [comment] 2017-06-14 06:55
Any solutions yet?

**Comment by dunwen** [comment] 2017-06-26 07:24
use glide solve this problem..............

**Comment by CoolMind** [comment] 2018-02-26 16:22
Do you really need such a large image? Simple resize it to a bitmap, then make all you want.

`Bitmap bitmap = Picasso.with(getContext()).load(uri).resize(2000, 0).get();`

**Comment by JakeWharton** [comment] 2018-03-03 01:51
Dupe of https://github.com/square/picasso/issues/754

**Closed by JakeWharton** 2018-03-03 01:51 UTC
