### ISSUE TITLE
picasso can not resize big image from sdcard

### ISSUE THREAD

**Issue by a1154043439** [square/picasso#1248] opened 2015-12-29 07:15 UTC
I use picasso like this:
Picasso.with(context)
.load(uri)
.resize(200,200)
.placeholder(R.color.pc_title_bar).error(R.drawable.pd_empty_picture).into(target);
if image is small,it will work ,but it load failed resize image while image is big,for example ,dimension like this:
 D/skia: jpeg_decoder mode 0, config 6, w 3936, h 5248, sample 1, bsLength 582800!!
if I remove resize(200,200),it can load big image ,but  counter with an OOM error,so what can I do to load big image from sdcard.
here is my picasso version:
 'com.squareup.picasso:picasso:2.5.2'

**Comment by a1154043439** [comment] 2015-12-29 07:17
It seems resize() not work while load big image from sdcard

**Comment by Spground** [comment] 2016-01-11 03:36
yeah,I also encountered the same problem! My picasso version: 'com.squareup.picasso:picasso:2.5.2'
I guess this reason may be its MarkableInputStream Class, which is a InputSream wrapper.At the same time, i traced the error occured at decodeStream() method in BitmapHunter Class,

**Comment by Spground** [comment] 2016-01-11 03:36
![om446d mq xc 4vf0ztw5t6](https://cloud.githubusercontent.com/assets/10492823/12226468/848fba26-b857-11e5-96dd-e4338eb8474c.png)

**Comment by DolphinBoy** [comment] 2016-01-19 02:21
Solved?

**Comment by a1154043439** [comment] 2016-01-19 02:53
I don't know why ,but I solved my problem this way:
use
compile 'com.squareup.picasso:picasso:2.4.0'
instead of
compile 'com.squareup.picasso:picasso:2.5.2'

**Comment by JakeWharton** [comment] 2016-01-26 17:17
Dupe of #364

**Closed by JakeWharton** 2016-01-26 17:17 UTC
