### ISSUE TITLE
Andorid Studio Arctic Fox is not detecting new version 2.8

### ISSUE THREAD

**Issue by m-asadullah** [square/picasso#2211] opened 2021-07-30 12:03 UTC
Here is screenshot of the issue

![Screenshot AndroidStudio Arctic Fox](https://user-images.githubusercontent.com/68208088/127650137-891f5b82-edc2-4d78-bad4-56cd20f636f3.png)

**Comment by JakeWharton** [comment] 2021-07-30 12:39
Dupe of #2179

**Closed by JakeWharton** 2021-07-30 12:39 UTC
