### ISSUE TITLE
 I get half photo and half white color, and sometimes I get only the white color.

### ISSUE THREAD

**Issue by Kuoyhout** [square/picasso#836] opened 2015-01-06 12:56 UTC
I try to load photo in to girdview sometimes a few photos show only half photo and white color for other half, and some the photos show only white color just like the screenshot below.

![15 - 2](https://cloud.githubusercontent.com/assets/5210467/5628737/e519fade-95dd-11e4-8c70-e8369eb36ad9.jpg)
![15 - 1](https://cloud.githubusercontent.com/assets/5210467/5628742/ec230762-95dd-11e4-8426-ea48d180cb4c.jpg)

**Comment by JakeWharton** [comment] 2015-01-06 17:18
What version of Picasso? Does it always happen with the same url? What shows up in the logs? Can you reproduce it reliably?

I suspect this has nothing to do with Picasso and it Android's bitmap decoder.

**Comment by dnkoutso** [comment] 2015-01-06 18:23
You can also try another image loading library and see if this issue occurs.

If it does, can you please provide a sample app so we can fix in Picasso as well?

**Comment by Kuoyhout** [comment] 2015-01-07 02:12
@JakeWharton I'm using version 2.4.0. It doesn't happen with the same url but when the photo show only half or show only white color, it will stay that way when the photo reload from cache. It doesn't usually happen, sometimes it's working fine, sometimes it give me this issues. I forget to copy the logs when this happen.

@dnkoutso I only know how to use Picasso and Universal image loader. I used to use universal image loader, I didn't get this issue, but I got another issue so I switched to Picasso.

**Comment by 6a209** [comment] 2015-01-07 06:10
I also encountered this problem

**Comment by jacobtabak** [comment] 2015-01-12 16:04
I am intermittently experiencing the same issue.  Source photo had just been taken with the Nexus 6 camera on Android 5.0.1 and had been loaded with FileRequestHandler.

![screenshot](http://i.imgur.com/2opRDdX.jpg)

**Comment by jacobtabak** [comment] 2015-01-12 21:40
@Kuoyhout what device are you experiencing this on?  We are seeing it happen exclusively on Nexus 6.

**Comment by Kuoyhout** [comment] 2015-01-13 00:00
@jacobtabak I experience this on my Galaxy Note 4

**Comment by dnkoutso** [comment] 2015-01-13 00:02
If it works on another image loading library I'd like for us to tackle this for Picasso. @Kuoyhout got a sample app?

**Comment by Kuoyhout** [comment] 2015-01-13 00:07
@dnkoutso sorry, I don't have any sample app. @jacobtabak Do you have any sample app?

**Comment by jacobtabak** [comment] 2015-01-13 01:18
I will try to throw together a sample app tomorrow.  I don't have a device that can reproduce the issue but I'll have one of our testers verify the sample app reproduces the issue.  He said it happens about 90% of the time.

@6a209 what device can you reproduce the issue on, and how often does it happen?

**Comment by 6a209** [comment] 2015-01-13 03:20
@jacobtabak I was use NetworkRequestHandler not FileRequestHandler
when the internet suddenly gone it must happen

**Comment by allanhtt** [comment] 2015-01-15 08:38
i still has this problem , i think is really a bug , it happens lot of times  , but can not repeat hard. 
i still think it is happended in bad network . a half of image download and be cached . next time ,when  the app be opened , picasso get the bad image from cache and display to the view .
so why the bad image can be cached ?

**Comment by 6a209** [comment] 2015-01-15 08:45
@allanhtt  because Picasso not check the content-length

**Comment by K-Constantine** [comment] 2015-01-27 14:44
check your ImageView tag in xml. i think that's where the problem is from... kindly remove the  android:scaleType attribute and check to see if error still exists. Do not quote me on this though. I usually dont get that error when  remove the scaleType attribute from the ImageView and use the fit() method in picasso which is reliable

**Comment by viveksinha121** [comment] 2015-05-28 07:13
Hi,
Anyone got solution for above problem?
I have still this problem. Frequently occurring on 2G network.

**Comment by K-Constantine** [comment] 2015-05-28 07:16
Did you use a custom ImageViewer?

**Comment by viveksinha121** [comment] 2015-05-28 12:00
No,
There is no custom imageview in my app.
There is a listview in which I am displaying Image using ImageView and a text using textView.

**Comment by viveksinha121** [comment] 2015-05-29 05:46
I think there is no solution because Picasso convert Inputstream into image and treat it as successful even if it failed to load full image.
I just want to avoid caching of such images which are not loaded fully.
Is there anything to do in this?

**Comment by viveksinha121** [comment] 2015-05-29 13:57
Can I measure the dimension of images loaded using Picasso in ImageView?
If possible then I can avoid caching of images which are not loaded as per desired dimension.

**Comment by K-Constantine** [comment] 2015-05-29 14:09
Picaso does caching already. What properties do you have in the image tag?
I know scaleType could cause such issue

**Comment by viveksinha121** [comment] 2015-05-29 17:16
Yes.
I have scaleType fitXY in image view.

**Comment by K-Constantine** [comment] 2015-05-29 17:45
Try removing the scaleType property in the image viewer

**Comment by viveksinha121** [comment] 2015-05-30 05:15
I removed scaleType but now my image is not displayed as I want.
I used .fit() of picasso but it has same problem as with scaletype.

**Comment by K-Constantine** [comment] 2015-05-30 06:21
One more favour. Can you paste the image tag here? And please did you set a
placeholder for error downloading images? Sounds strange on this behaviour

**Comment by viveksinha121** [comment] 2015-05-30 08:29
<ImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="220dp" />

Picasso.with(context)
				.load(url)
				.placeholder(R.drawable.placeHolder)
				.error(R.drawable.error)
				.fit()
				.into(imageView);

**Comment by K-Constantine** [comment] 2015-05-30 09:17
try using one instance of picasso to across every image loader... it could
be thread issues i think


import com.squareup.picasso.Picasso;

/**
 * Created by root on 12/19/14.
 */
public class Application extends android.app.Application implements
HttpResponseInterceptor
{

    private static Application INSTANCE;

    private boolean debugMode;
    private Picasso picassoInstance;

    @Override
    public void onCreate()
    {
        super.onCreate();
        debugMode = true;
        INSTANCE = this;
        setPicassoInstance();
    }

    public boolean isDebugMode()
    {
        return this.debugMode;
    }

    private void setPicassoInstance()
    {
        picassoInstance = new
Picasso.Builder(getApplicationContext()).build();
        picassoInstance.setDebugging(debugMode);
        Picasso.setSingletonInstance(picassoInstance);
    }

    public static synchronized Application getINSTANCE()
    {
        return INSTANCE;
    }

    public Picasso getPicassoInstance()
    {
        return picassoInstance;
    }
}













Application.getINSTANCE().getPicassoInstance().load(uri)
                .error(R.drawable.ic_error_placeholder)

.placeholder(R.drawable.ic_placeholder).fit().into(imageView);

**Comment by K-Constantine** [comment] 2015-05-30 09:27
load images like this Application.getINSTANCE().
getPicassoInstance().load(uri)
                .error(R.drawable.ic_error_placeholder)

.placeholder(R.drawable.ic_placeholder).fit().into(imageView);

**Comment by viveksinha121** [comment] 2015-05-30 12:00
Can anyone please explain what exactly happens when 
Picasso.with(context).load(url).into(imageView);
is called?

**Comment by chushuangqi** [comment] 2016-01-26 03:47
@6a209 How to use your fixed version?

**Comment by shubhamchaudhary** [comment] 2016-02-12 08:13
Facing the same issue with `picasso.load().into()` call

**Comment by ayalma** [comment] 2016-02-29 13:53
I faced with same problem . but i trying to load my images form asset folder.
and in log cat i get out of memory exception.

**Comment by ankur-funongo** [comment] 2016-04-28 08:18
Facing this issue sometimes when network connectivity is low. Is it possible to check download image dimension & if it is not of full dimension as expected then we can conclude that image is partially downloaded? Or is it that dimension we get would always be full due to already downloaded image header?

**Comment by SwiftyWang** [comment] 2017-07-14 02:04
still has this problem in 2.5.2 version...

**Comment by songzhiyong** [comment] 2017-07-27 04:08
@SwiftyWang how do you fix it？

**Comment by songzhiyong** [comment] 2017-07-27 04:19
Still no solution?

**Comment by almaz010891** [comment] 2017-10-20 12:41
Facing the same issue with picasso.load().into() call

**Comment by MuhammedRefaat** [comment] 2018-05-17 04:19
Unfortunately I will shift to another library because of that issue.

**Comment by JakeWharton** [comment] 2018-10-20 14:47
Fixed by #2001

**Closed by JakeWharton** 2018-10-20 14:47 UTC

**Comment by rajeshthori** [comment] 2019-03-11 07:57
this is my code i am getting image is blank
 protected void onActivityResult(int requestCode, int resultCode, Intent data) {

        try {
            // When an Image is picked
            if (requestCode == Utils.REQCODE && resultCode == RESULT_OK
                    && null != data) {
                // Get the Image from data

                String[] filePathColumn = { MediaStore.Images.Media.DATA };
                imagesUriList = new ArrayList<Uri>();
                encodedImageList.clear();
                if(data.getData()!=null){

                    Uri mImageUri = data.getData();

                    // Get the cursor
                    Cursor cursor = getContentResolver().query(mImageUri,
                            filePathColumn, null, null, null);
                    // Move to first row
                    cursor.moveToFirst();

                    int columnIndex = cursor.getColumnIndex(filePathColumn[0]);

                    imageURI  = cursor.getString(columnIndex);
                    Bitmap bitmap = MediaStore.Images.Media.getBitmap(this.getContentResolver(), mImageUri);
                   /* ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    bitmap.compress(Bitmap.CompressFormat.PNG, 100, baos);
                    byte[] b = baos.toByteArray();
                    String encodedImage = Base64.encodeToString(b,
                            Base64.DEFAULT);*/

                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    bitmap.compress(Bitmap.CompressFormat.PNG, 100, baos);
                    String encodedImage= Base64.encodeToString(baos.toByteArray(), Base64.DEFAULT);

                   // Log.d(TAG, "getStringImage: "+encodedImage.trim());
                    //return encodedImage;
                    //ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
                   // bitmap.compress(Bitmap.CompressFormat.PNG, 70, byteArrayOutputStream);
                   // String encodedImage = Base64.encodeToString(byteArrayOutputStream.toByteArray(), Base64.NO_WRAP);
                    encodedImageList.add(encodedImage);
                    cursor.close();
