### ISSUE TITLE
Failed to add custom RequestHandler

### ISSUE THREAD

**Issue by emanonwzy** [square/picasso#807] opened 2014-12-22 16:20 UTC
Hi,

Trying to use Picasso.Builder to add custom RequeseHandler,  the code snipe as below:

```Java
    public void loadImage(final Context context, final String imgId, 
                          final String url, final WebImageLoaderCallback callback) {
        Downloader downloader = new OkHttpDownloader(context);
        Picasso.Builder builder = new Picasso.Builder(context)
                .downloader(downloader)
                .addRequestHandler(new WebImageRequestHandler(downloader, imgId, callback));
        builder.build().load(url).skipMemoryCache().tag(url).fetch();
    }	
```

After load some images, get the followed errors:
> Looper:    could not create wake pipe. errno=24

Is this the right way to add custom RequestHandler?

Thanks.

**Comment by dnkoutso** [comment] 2015-01-01 23:21
Are you re-creating Picasso instances for every `loadImage` call? Should be using a singleton and apply your request handler once.

**Comment by emanonwzy** [comment] 2015-01-02 13:18
@dnkoutso  Thanks for reply. Yes, I re-creating Picasso instances for every loadImage call. But analysed code I don't know why the error happens. Could you explain the reason? Thanks.

**Comment by dnkoutso** [comment] 2015-01-02 17:13
Please do not use a single Picasso instance just for a single load. This could be the cause of the problem too although I am not sure 100%.

**Comment by JakeWharton** [comment] 2015-01-08 06:35
Without more information we have no way of knowing what the problem is or if it even is Picasso's fault. If you get a complete stack trace or anything more than a partial log message we'll happily take a closer look.

Closing for now.

**Closed by JakeWharton** 2015-01-08 06:35 UTC
