### ISSUE TITLE
Picasso failed to load a particluar image url. 

### ISSUE THREAD

**Issue by HenryChao24** [square/picasso#1277] opened 2016-01-28 17:13 UTC
Hi,  @JakeWharton 
URL is as follows:
private static final String URL = "http://img3.imgtn.bdimg.com/it/u=1183223528,3058066243&fm=21&gp=0.jpg";
It's normal to view the image with Chrome,yet failed with Picasso.
thanks first.

**Comment by JakeWharton** [comment] 2016-01-28 17:15
With what error?

**Comment by HenryBrightChao** [comment] 2016-01-31 05:32
Thanks for response@JakeWharton 
Sadly,there's no error shown on LogCat.
Yet,I found it's successful when i request the particluar img in getView() .For example:

    // MyAdapter...
    @Override
    public void onBindViewHolder(final MainViewHolder holder, int position) {
          Picasso.with(mContext).load("http://img3.imgtn.bdimg.com/it/u=1183223528,3058066243&fm=21&gp=0.jpg").into(mImageView);
    }

However,if i directly request the same img in onCreate(..)  of Activity .For example:

    //MyActivity
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Picasso.with(mContext).load("http://img3.imgtn.bdimg.com/it/u=1183223528,3058066243&fm=21&gp=0.jpg").into(mImageView);
    }
It failed then.

**Comment by khanal-abhi** [comment] 2016-02-29 22:56
@HenryBrightChao, it's because of the activity life cycle more than likely. By the time you are in onCreate, mImageView is still null. onCreateView is when the view is loaded and (hopefully) you have referenced the correct view from the layout. Hope that helps.

**Comment by JakeWharton** [comment] 2018-03-03 03:12
You can enable debug logging and attach an error listener to the Picasso instance to figure out what the cause of this is. Without this information, there's no action to take. Preemptively closing due to age.

**Closed by JakeWharton** 2018-03-03 03:12 UTC
