### ISSUE TITLE
Android Studio shows a strange version

### ISSUE THREAD

**Issue by NathanFallet** [square/picasso#2314] opened 2022-08-21 09:31 UTC
Android Studio wants me to update my version of picasso, but this looks strange... what is it?
<img width="705" alt="image" src="https://user-images.githubusercontent.com/30439790/185784750-ad57829c-3537-414c-bfe0-fd6460eca0ce.png">

**Comment by sdfgsdfgd** [comment] 2022-09-04 10:43
SAME HERE SOMEONE HELP US I'm getting the exact same error, it's trying to force me to downgrade from 2.8 to 2.71828

**Comment by sdfgsdfgd** [comment] 2022-09-05 04:26
HELPPP

**Comment by jrodbx** [comment] 2022-09-05 06:00
Duplicate of #2179

**Closed** 2022-09-05 06:00 UTC
