### ISSUE TITLE
StrictMode - A resource was acquired at attached stack trace but never released.

### ISSUE THREAD

**Issue by Donava** [square/picasso#864] opened 2015-02-03 08:05 UTC
I'am using picasso 2.4.0, okhttp 2.2.0. I change picasso to 2.3.4 and okhttp 2.0.0 the problem also exists. 

<pre>
02-03 15:12:26.598  15983-15992/com.snda.mhh E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.util.zip.Inflater.<init>(Inflater.java:82)
            at okio.GzipSource.<init>(GzipSource.java:62)
            at com.squareup.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:535)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:717)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:431)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:376)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:471)
            at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:105)
            at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:49)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)
</pre>

When I load imageView in viewpage PagerAdapter, and url return 404. 

<pre>
@Override
        public Object instantiateItem(ViewGroup container, int position) {
            View view = LayoutInflater.from(mContext).inflate(R.layout.view_ad, container, false);
            final ImageView iv = (ImageView) view.findViewById(R.id.imageView);
            final ViewPager viewPager = (ViewPager) container;
            viewPager.addView(iv, 0);
            final BannerResponse.Banner banner = bannerList.get(position);
            Picasso.with(mContext).load(banner.url).into(iv);
            return view;
        }
</pre>

**Comment by JakeWharton** [comment] 2015-02-03 08:09
This could be a bug in OkHttp, Okio, or Picasso. Also potentially a dupe of #296.

**Comment by Amosiper** [comment] 2016-03-02 08:07
@JakeWharton, already fixed?

**Comment by heronghua** [comment] 2017-02-08 08:55
Could anybody tell whether this bug was fixed or not?

**Comment by JakeWharton** [comment] 2017-02-24 05:51
This was a bug in OkHttp that has been fixed for some time.

**Closed by JakeWharton** 2017-02-24 05:51 UTC
