### ISSUE TITLE
Suppot vor Vector resources

### ISSUE THREAD

**Issue by brinkkemper** [square/picasso#1307] opened 2016-03-06 13:28 UTC
When using the relatively new vector resources nothing is drawn

for instance 

**sleepy.xml**

```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="100dp"
        android:height="100dp"
        android:viewportWidth="100.0"
        android:viewportHeight="100.0">
    <path
        android:fillColor="#00b335"
        android:pathData="M75.8,75.8c7.1,-7.1 10.7,-15.7 10.7,-25.8s-3.6,-18.7 -10.7,-25.8c-0.4,-0.4 -0.9,-0.8 -1.3,-1.2c-6.9,-6.3 -15,-9.5 -24.5,-9.5c-10.1,0 -18.7,3.6 -25.8,10.7c-7.1,7.1 -10.7,15.7 -10.7,25.8s3.6,18.7 10.7,25.8c7.1,7.1 15.7,10.7 25.8,10.7c9.5,0 17.6,-3.1 24.5,-9.4C74.9,76.6 75.4,76.2 75.8,75.8M50,17.2c9.1,0 16.8,3.2 23.2,9.6c1.2,1.2 2.3,2.5 3.3,3.8c4.2,5.6 6.3,12.1 6.3,19.4c0,7.3 -2.1,13.8 -6.3,19.4c-1,1.3 -2.1,2.5 -3.3,3.8c-6.4,6.4 -14.1,9.6 -23.2,9.6c-9,0 -16.8,-3.2 -23.2,-9.6c-6.4,-6.4 -9.6,-14.1 -9.6,-23.2s3.2,-16.8 9.6,-23.2C33.2,20.4 41,17.2 50,17.2M50,51.8c-2.7,0 -4.9,1 -6.8,2.9c-1.9,2.1 -2.9,4.6 -2.9,7.5c0,2.9 1,5.3 2.9,7.2c1.8,2.1 4.1,3.1 6.8,3.1c2.8,0 5.1,-1 7,-3.1c1.8,-2 2.7,-4.4 2.7,-7.2c0,-2.9 -0.9,-5.4 -2.7,-7.5C55.1,52.7 52.8,51.8 50,51.8M25.5,42.8c-0.3,0.6 -0.4,1.2 -0.2,1.8c0.2,0.6 0.6,1.1 1.2,1.4c0.6,0.3 1.2,0.3 1.8,0.1l11.1,-3.6c0.6,-0.2 1.1,-0.6 1.4,-1.2c0.3,-0.6 0.3,-1.2 0.1,-1.8c-0.2,-0.6 -0.6,-1.1 -1.2,-1.3c-0.6,-0.3 -1.2,-0.4 -1.8,-0.2l-11.1,3.6C26.2,41.8 25.8,42.2 25.5,42.8M62.1,38c-0.6,-0.2 -1.3,-0.2 -1.8,0.2c-0.6,0.3 -1,0.7 -1.2,1.3c-0.2,0.6 -0.1,1.3 0.2,1.8c0.3,0.6 0.7,1 1.4,1.2l11.1,3.6c0.6,0.2 1.2,0.1 1.8,-0.1c0.4,-0.2 0.8,-0.5 1,-1c0.1,-0.1 0.1,-0.3 0.2,-0.4c0.2,-0.6 0.1,-1.3 -0.1,-1.8c0,0 -0.1,-0.1 -0.1,-0.1c-0.3,-0.5 -0.7,-0.9 -1.3,-1.1L62.1,38z"/>
</vector>

```

**Comment by JakeWharton** [comment] 2016-03-06 21:27
Dupe of #1109.

**Closed by JakeWharton** 2016-03-06 21:27 UTC
