### ISSUE TITLE
Picasso does not find images in the drawable-night folder

### ISSUE THREAD

**Issue by frankyxcs** [square/picasso#2097] opened 2019-07-24 01:47 UTC
Hi 

soon with Android Q the night mode will be very important in my opinion and it would be nice if you can fix this little problem. Picasso does not find pictures in the following directories:

drawable-night
drawable-night-hdpi    (also mdpi, xhdpi, xxhdpi and xxxhdpi)

Greets

Frank

**Comment by JakeWharton** [comment] 2019-07-24 13:41
Dupe of #1275. The title of that issue is a bit off, but it reflects the same desire.

**Closed by JakeWharton** 2019-07-24 13:41 UTC
