### ISSUE TITLE
onlyScaleDown not working when resize width or height is zero

### ISSUE THREAD

**Issue by kevinvanmierlo** [square/picasso#1651] opened 2017-07-19 11:48 UTC
I use the resize method with the height as zero to keep the aspect ratio of the image.
The downside of this is that the onlyScaleDown method is no longer working as expected. I assume because the height is zero it thinks the image should always be scaled down. Here is an example:

```Kotlin
Picasso.with(ctx)
    .load(imageUrl)
    .resize(imageView.width, 0)
    .onlyScaleDown()
    .into(imageView)
```

The image width is 984px and the image has a size of 50px by 50px. But with the resize function it now gets scaled up to 984px by 984px.

I understand that this is happening, but my expectation was that it would remain 50px by 50px.

**Comment by JakeWharton** [comment] 2017-07-19 14:03
Dupe of #1432. This is fixed on `master`.

**Closed by JakeWharton** 2017-07-19 14:03 UTC

**Comment by kevinvanmierlo** [comment] 2017-07-19 14:07
@JakeWharton Glad it's fixed! Do you have any indication when the new version will be released?

**Comment by JakeWharton** [comment] 2017-07-20 00:36
Not at this time. There's still ongoing work towards it since it's a major
version bump.

**Comment by kevinvanmierlo** [comment] 2017-07-20 07:09
@JakeWharton Okay thanks, looking forward to the update!
