### ISSUE TITLE
Loading and saving images into file on sd card

### ISSUE THREAD

**Issue by ViHtarb** [square/picasso#1139] opened 2015-09-14 22:28 UTC
How make loading and saving images into file? 
I try use this method:

``` java
private Target target = new Target() {
    @Override
    public void onBitmapLoaded(final Bitmap bitmap, Picasso.LoadedFrom from) {
        File file = new File(Environment.getExternalStorageDirectory().getPath()  + "/saved.jpg");
        try {
            file.createNewFile();
            FileOutputStream ostream = new FileOutputStream(file);
            bitmap.compress(Bitmap.CompressFormat.JPEG,100,ostream);
            ostream.close();
         } catch (Exception e) {
            e.printStackTrace();
         }
    }

    @Override
    public void onBitmapFailed(Drawable errorDrawable) {}

    @Override
    public void onPrepareLoad(Drawable placeHolderDrawable) {}
};

@Override
public void onClick(View v) {
    Picasso.with(context).load("url").into(target);
}
```

On first click calling only `onPrepareLoad` method.
Method `onBitmapLoaded` calling only on second and more clicks.

I need to calling `onBitmapLoaded` method on first click.

PS. images for loading in HD size;
PSS. if loading smaller images all wonderful

**Comment by luccasmaso** [comment] 2015-11-24 13:55
You can simplify and let the [`OkHttpDownloader`](https://square.github.io/picasso/2.x/picasso/com/squareup/picasso/OkHttpDownloader.html#OkHttpDownloader-java.io.File-long-) from Picasso to handle caching images to disk. Picasso supports disk caching through it's HTTP client.

For example:
```
       mBuilder = new Picasso.Builder(context)
                .loggingEnabled(BuildConfig.DEBUG)
                .indicatorsEnabled(BuildConfig.DEBUG)
                .downloader(new OkHttpDownloader(context, DISK_CACHE_SIZE))
                .build();
       
       mBuilder.load("url").into(target);
```

**Comment by LikeWather** [comment] 2016-03-15 05:38
have this?    

<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />

**Comment by LikeWather** [comment] 2016-03-15 05:39
`    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />`
have this

**Comment by jzeferino** [comment] 2016-03-22 23:45
@luccasmaso using the line `new OkHttpDownloader(context, DISK_CACHE_SIZE)` will cache all downloaded images to disk?

**Comment by luccasmaso** [comment] 2016-03-22 23:51
As far as I know, yes. 
https://square.github.io/picasso/2.x/picasso/com/squareup/picasso/OkHttpDownloader.html#OkHttpDownloader-java.io.File-long-

Read more about this in this stackoverflow answer: http://stackoverflow.com/a/23281195/255932

**Comment by altaf933** [comment] 2016-06-23 03:55
I have implemented this function by a interface after downloaded successfully than it will callback into my class.

**Comment by JakeWharton** [comment] 2018-03-03 03:14
This seems like a dupe of #506.

**Closed by JakeWharton** 2018-03-03 03:14 UTC
