### ISSUE TITLE
Sometimes the images are randomly swapped when loaded from cache

### ISSUE THREAD

**Issue by tfKamran** [square/picasso#1475] opened 2016-08-20 12:19 UTC
I am using it Picasso in a `GridView` adapter like:

```
Picasso.with(getActivity())
        .load(Uri.parse(item.getItemIconUrl()))
        .placeholder(R.drawable.icon_placeholder)
        .into(viewHolder.imageView);
```

The first time it loads the images perfectly (when it is fetched from a remote URL), but loads a completely random image from cache the next time for a few items in the list.

Before integrating Picasso, this issue was not evident with the application being used for months.

This issue is rarely reproduced. I have still not figured out the exact scenario.

**Comment by JakeWharton** [comment] 2016-08-20 23:06
Unless you can provide a reproduction test or sample there's nothing we can really do here. Your report doesn't contain any actionable information for us.

**Comment by Mindbowser** [comment] 2016-09-01 07:26
I am also facing the same issue in my app. Similarly, I am using a GridView & initially it loads the correct images without any glitches but when I refresh the view then it shows some random images for few moments & then shows the correct ones.

So in my case on refreshing the view, it shows the issue.

**Comment by JakeWharton** [comment] 2016-09-01 12:53
Can you provide a sample that demonstrates the issue?

**Comment by 4k3R** [comment] 2016-10-14 14:57
I'm also facing similar issue. I've a RecyclerView with a list of image URL's coming from the server. I've set if condition to check whether there is image URL or not. If there is no image URL, then I set another image (default one). But sometimes while scrolling, image url from another index is set on the ImageView, kind of like loading cached image on wrong index.

I don't know if this helps, but this is the code used in onBindViewHolder of RecyclerView adapter

            if (!eventsList.get(position).getBannerUrl().isEmpty()) {
                Picasso.with(context).load(eventsList.get(position).getBannerUrl()).placeholder(R.mipmap.placeholder).into(holder.imageViewBanner);
            } else {
                holder.imageViewBanner.setImageResource(R.mipmap.placeholder);
            }

**Comment by gen0083** [comment] 2016-11-10 09:55
I met similar issue using in RecyclerView and DataBinding.
I use Picasso to fetch a favicon from the item's url.

Run app then create and bind view holder position 0 to 10 in RecyclerView (in case of Nexus5).
But items at position 6 to 10 are not visible.
I scrolled items then re-bind view holder at position 6.
And then the favicon at position 6 was not correctly, it showed the position 7's.

I think It comes from that view holder's instance was not same between first time and second time onBindViewHolder.
I call cancelRequest but it was not worked expectedly.

```
        Picasso.with(context)
                .cancelRequest(binding.favicon);
        Picasso.with(context)
               .load(FAVICON_URL + item.getLink())
               .placeholder(R.drawable.favicon_placeholder)
               .error(R.drawable.favicon_placeholder)
               .fit()
               .into(binding.favicon);
```

Abobe code in https://github.com/gen0083/FilteredHatebu/blob/develop/app/src/main/java/jp/gcreate/product/filteredhatebu/ui/feedlist/FeedAdapter.java

**Comment by jimitpatel** [comment] 2016-11-25 11:51
is there any solution for the above problem for recyclerview and picasso? I am facing similar issue with my code.

I am using GridLayoutManager with 2 columns and I am getting this issue for 3rd and 4th position if position is starting from 0. But after scrolling down and coming back up it is showing proper. Or if I click on that item and come back it shows proper image.

This is what I have implemented for displaying image:

```
public static void setImage(final Context context, final CustomImageView img, @DrawableRes final int defId,
                                @DrawableRes final int errId, final String path) {
        if (null != img.getTag()) {
            Picasso picasso = PicassoCache.getPicassoInstance(context);
            picasso.setIndicatorsEnabled(false);
            if (TextUtils.isEmpty(path)) {
                if (BuildConfig.DEBUG)
                    Log.d(TAG, "setImage: nullpath tag=" + img.getTag() + ", path=" + path);
                img.setImageResource(defId);
            } else {
                try {
                    picasso.load(path)
                            .placeholder(defId)
                            .error(errId)
                            .fit()
                            .centerInside()
                            .tag(context)
                            .noFade()
                            .into(img);
                    if (BuildConfig.DEBUG)
                        Log.d(TAG, "setImage: setting tag=" + img.getTag() + ", path=" + path);
                } catch (Exception e) {
                    if (BuildConfig.DEBUG)
                        Log.d(TAG, "setImage: exception tag=" + img.getTag() + ", path=" + path);
                    img.setImageResource(defId);
                }
            }
        } else {
            if (BuildConfig.DEBUG)
                Log.d(TAG, "setImage: tag=null, path=" + path);
            img.setImageResource(defId);
        }
    }
```

And in bind view this is the piece of code:

```
public void bindViews(int position, Product product, IOnApiRequestComplete callback) {
        chkWishlist.setChecked(product.isWishlist());
        chkWishlist.setTag(product);
        chkWishlist.setPosition(position);
        chkWishlist.setApiRequestCompleteListener(callback);

        if (product.isInStock()) {
            lblNewTag.setVisibility(product.isNew() ? View.VISIBLE : View.GONE);
        } else {
            lblNewTag.setVisibility(View.GONE);
        }

        if (BuildConfig.DEBUG)
            Log.d(TAG, "onBindViewHolder: position=" + getAdapterPosition());

        PicassoHelper.setImage(context, imgProduct, R.drawable.placeholder_product, R.drawable.placeholder_product,
                product.getProductThumbnailArrayList().get(0).getThumb());

        lblBrand.setText(product.getBrandName());
        lblPrice.setText(Utils.formatString(product.getShopArrayList().get(0).getPrice(), "###,###.##"));

        imgStock.setVisibility(product.isInStock() ? View.GONE : View.VISIBLE);
        lblOutOfStock.setVisibility(product.isInStock() ? View.GONE : View.VISIBLE);
        itemView.setTag(product);
        itemView.setId(position);
    }
```

**Comment by b12kab** [comment] 2018-03-17 17:24
I've also come across this issue as well with version 2.5.2. 

What my code is doing is fetching 4 different types of movie groups. Since they are the same information, I put them in the same [Realm](https://realm.io/docs/java/latest) object store. As each movie group network load finishes and the next one movie set loads, the [RealmRecyclerView](https://github.com/m2f/realm-recyclerview) takes that as a change and re-loads the view. The image cache works properly for many of the images, but the incorrect cache hit will show up on average probably every 2-3 refreshes.

[Here is a GIF that shows the cache problem.](https://bitbucket.org/b12kab/picassocacherrorgif/src/27f689f2da2587fa1cffe4565103280316424304/cache-problem-1a.gif?at=master&fileviewer=file-view-default)

I've created a stripped down version (shown in the GIF) of my project code that will (eventually) show the cache problem. 

It's not open source, over on Bitbucket. If one of this repository maintainers would like to see it, they can send me a email and I'll add them to that repo.

**Comment by rhonyabdullah** [comment] 2018-04-14 23:52
Hello, i'm also facing this issue, any updates ?

**Comment by JakeWharton** [comment] 2018-04-16 22:57
@captswag Your code is broken. Call `Picasso.cancelRequest ` in the `else`.

@gen0083 What version are you using. There was a bugfix that only made it into version 2.7 which is not in 2.5 or lower with RecylerView.

@jimitpatel Your code is broken. Call `Picasso.cancelRequest ` inside the nested `if` and in the outer `else`.

Closing without a sample that reproduces the behavior. Thus far is seems like incorrect usage of the library or use of an older version are the causes.

If someone can provide a sample app that demonstrates the problem we'd be happy to look. The sample is a great place to start.

**Closed by JakeWharton** 2018-04-16 22:57 UTC
Labels: Needs Info

**Comment by b12kab** [comment] 2018-04-17 15:54
@JakeWharton What is your Bitbucket id? I'll add you to my sample project that shows this.

**Comment by CurtesMalteser** [comment] 2018-07-29 20:54
Hello, I'm facing the same issue.
` void bind(int listIndex) {
            final Event event = mEvents.get(listIndex);
            if (event.image() != null) {
                Picasso.get()
                        .load(event.image().medium().url())
                        .networkPolicy(NetworkPolicy.OFFLINE)
                        .into(ivCardPlacePhoto, new Callback() {
                            @Override
                            public void onSuccess() {
                            }
                            @Override
                            public void onError(Exception e) {
                                Picasso.get()
                                        .load(event.image().medium().url())
                                        .placeholder(R.drawable.ic_launcher_background)
                                        .error(R.drawable.ic_launcher_background)
                                        .into(ivCardPlacePhoto);
                            }
                        });
            } else {
                Picasso.get().cancelRequest(ivCardPlacePhoto);
                ivCardPlacePhoto.setBackgroundResource(R.drawable.ic_launcher_background);
            }
        }`

The full adapter code can be found here: [https://github.com/CurtesMalteser/Capstone-Project/blob/master/PingPoinz/app/src/main/java/com/curtesmalteser/pingpoinz/activity/adapter/PoinzPlacesAdapter.java](url)

If only one or two images are missing, everything works properly, but in this particular case, the API call returns only five images from a total of 45 results. This means that if I keep scrolling the recyclerview from top to bottom and vice-versa, I can end with all the placeholders replaced with these 5 images.

**Comment by kazisane** [comment] 2019-12-28 09:00
![img](https://user-images.githubusercontent.com/57387434/71541417-9162a280-297e-11ea-80df-555e14e70ea7.png)

**Comment by jimitpatel** [comment] 2020-05-12 06:53
> @jimitpatel Your code is broken. Call `Picasso.cancelRequest ` inside the nested `if` and in the outer `else`.

Oh!! that was the problem. I think document needs to be revisited. Thanks :)

**Comment by ferranm99** [comment] 2022-01-22 19:49
Can somebody tell me how did you get through this issue? I am facing this exact problem and it is really annoying. thanks in advance!
