### ISSUE TITLE
[Feature Request] Add ability to download image file only

### ISSUE THREAD

**Issue by Piasy** [square/picasso#1527] opened 2016-11-10 01:51 UTC
As we know, picasso doesn't optimize for big image, e.g. 4000*4000, and I've create a library https://github.com/Piasy/BigImageViewer that use https://github.com/davemorrissey/subsampling-scale-image-view to show big image, but we can't load the image into memory as a Bitmap, because it will cost huge amount of memory.

So I need get the downloaded file, either cache hit or miss, Fresco and Glide all supports this feature, could picasso add this?

Thanks!

**Comment by JakeWharton** [comment] 2016-11-10 02:06
Dupe of #506.

**Closed by JakeWharton** 2016-11-10 02:06 UTC
