### ISSUE TITLE
Picasso Get() method not loading images from URL. But closes the app.

### ISSUE THREAD

**Issue by BENNYKAVIL** [square/picasso#2087] opened 2019-05-25 15:27 UTC
package com.example.imageapp;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;

import android.app.Activity;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.AsyncTask;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.Toast;

import com.squareup.picasso.Callback;
import com.squareup.picasso.Picasso;

import static android.widget.Toast.LENGTH_SHORT;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String MY_URL_STRING ="http://www.geocities.ws/mariyanaatham/2019/may/1.png";
        ImageView iv = (ImageView) findViewById(R.id.iv);
        Picasso.get()
                .load(MY_URL_STRING)
                .into(iv, new Callback() {
                    @Override
                    public void onSuccess() {
                    }

                    @Override
                    public void onError(Exception e) {
                        e.printStackTrace();
                        String msg =e.getMessage();
                        Toast.makeText(getApplicationContext(),msg, LENGTH_SHORT).show();

                    }
                });

    }

}

Added internet permission in Manifest file as 👍 
    <uses-permission android:name="android.permission.INTERNET"/>
No Error messages. The app simply closes.

**Comment by JakeWharton** [comment] 2019-05-28 12:33
Can you provide a full sample project that reproduces the problem?

**Comment by demo7up** [comment] 2020-06-26 21:17
Im also having this same issue. Especially if the value is null

2020-06-26 17:02:23.257 27624-27729/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
2020-06-26 17:02:23.273 27624-27728/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
2020-06-26 17:02:23.525 27624-27687/com.example.livetvseries I/OpenGLRenderer: Davey! duration=2599ms; Flags=0, IntendedVsync=124378538717938, Vsync=124380372051198, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=124380376526800, AnimationStart=124380376568900, PerformTraversalsStart=124380380699600, DrawStart=124380922634800, SyncQueued=124381039577600, SyncStart=124381051502400, IssueDrawCommandsStart=124381055254300, SwapBuffers=124381148377700, FrameCompleted=124381150144400, DequeueBufferDuration=275500, QueueBufferDuration=802100, GpuCompleted=124379057261100, 
2020-06-26 17:02:23.584 27624-27624/com.example.livetvseries I/Choreographer: Skipped 49 frames!  The application may be doing too much work on its main thread.
2020-06-26 17:02:23.626 27624-27687/com.example.livetvseries I/OpenGLRenderer: Davey! duration=861ms; Flags=0, IntendedVsync=124380388657302, Vsync=124381205323936, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=124381209150200, AnimationStart=124381209180400, PerformTraversalsStart=124381214314600, DrawStart=124381214496400, SyncQueued=124381245054000, SyncStart=124381246455500, IssueDrawCommandsStart=124381246693600, SwapBuffers=124381249367400, FrameCompleted=124381251811800, DequeueBufferDuration=611500, QueueBufferDuration=1273400, GpuCompleted=124379071758700, 
2020-06-26 17:02:23.670 27624-27638/com.example.livetvseries I/le.livetvserie: Background concurrent copying GC freed 254281(9899KB) AllocSpace objects, 29(8332KB) LOS objects, 49% free, 9179KB/17MB, paused 5.779ms total 327.190ms
2020-06-26 17:02:23.679 27624-27640/com.example.livetvseries W/System: A resource failed to call close. 
2020-06-26 17:02:23.683 27624-27640/com.example.livetvseries W/System: A resource failed to call close. 
2020-06-26 17:02:23.800 27624-27727/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
2020-06-26 17:02:23.817 27624-27733/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
2020-06-26 17:02:24.334 27624-27727/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
2020-06-26 17:02:24.746 27624-27733/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
2020-06-26 17:02:25.895 27624-27680/com.example.livetvseries V/FA: Inactivity, disconnecting from the service

**Comment by plswiderski** [comment] 2021-02-06 18:28
Hey! As I see this issue is related to not closed OKHttp call. As I see it in OKHttp3Downloader line 91:

`  @NonNull @Override public Response load(@NonNull Request request) throws IOException {
    return client.newCall(request).execute();
  }`

Details about StrictMode error that tells that:

` StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1924)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:303)
        at java.io.FileOutputStream.finalize(FileOutputStream.java:492)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:259)
        at dalvik.system.CloseGuard.open(CloseGuard.java:230)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:253)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at okio.Okio.sink(Okio.java:181)
        at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:49)
        at okhttp3.internal.cache.DiskLruCache$Editor.newSink(DiskLruCache.java:899)
        at okhttp3.Cache$CacheRequestImpl.<init>(Cache.java:442)
        at okhttp3.Cache.put(Cache.java:254)
        at okhttp3.Cache$1.put(Cache.java:149)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:131)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.squareup.picasso.OkHttp3Downloader.load(OkHttp3Downloader.java:91)
        at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:46)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
        at com.squareup.picasso.RequestCreator.get(RequestCreator.java:429)`

I will test this with closing fix and let you know is it enough to solve this.

**Closed** 2021-02-11 04:21 UTC

**Comment by sarveshamrit** [comment] 2021-06-09 17:27
> Im also having this same issue. Especially if the value is null
> 
> 2020-06-26 17:02:23.257 27624-27729/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2020-06-26 17:02:23.273 27624-27728/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2020-06-26 17:02:23.525 27624-27687/com.example.livetvseries I/OpenGLRenderer: Davey! duration=2599ms; Flags=0, IntendedVsync=124378538717938, Vsync=124380372051198, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=124380376526800, AnimationStart=124380376568900, PerformTraversalsStart=124380380699600, DrawStart=124380922634800, SyncQueued=124381039577600, SyncStart=124381051502400, IssueDrawCommandsStart=124381055254300, SwapBuffers=124381148377700, FrameCompleted=124381150144400, DequeueBufferDuration=275500, QueueBufferDuration=802100, GpuCompleted=124379057261100,
> 2020-06-26 17:02:23.584 27624-27624/com.example.livetvseries I/Choreographer: Skipped 49 frames! The application may be doing too much work on its main thread.
> 2020-06-26 17:02:23.626 27624-27687/com.example.livetvseries I/OpenGLRenderer: Davey! duration=861ms; Flags=0, IntendedVsync=124380388657302, Vsync=124381205323936, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=124381209150200, AnimationStart=124381209180400, PerformTraversalsStart=124381214314600, DrawStart=124381214496400, SyncQueued=124381245054000, SyncStart=124381246455500, IssueDrawCommandsStart=124381246693600, SwapBuffers=124381249367400, FrameCompleted=124381251811800, DequeueBufferDuration=611500, QueueBufferDuration=1273400, GpuCompleted=124379071758700,
> 2020-06-26 17:02:23.670 27624-27638/com.example.livetvseries I/le.livetvserie: Background concurrent copying GC freed 254281(9899KB) AllocSpace objects, 29(8332KB) LOS objects, 49% free, 9179KB/17MB, paused 5.779ms total 327.190ms
> 2020-06-26 17:02:23.679 27624-27640/com.example.livetvseries W/System: A resource failed to call close.
> 2020-06-26 17:02:23.683 27624-27640/com.example.livetvseries W/System: A resource failed to call close.
> 2020-06-26 17:02:23.800 27624-27727/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2020-06-26 17:02:23.817 27624-27733/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2020-06-26 17:02:24.334 27624-27727/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2020-06-26 17:02:24.746 27624-27733/com.example.livetvseries D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2020-06-26 17:02:25.895 27624-27680/com.example.livetvseries V/FA: Inactivity, disconnecting from the service

How did you resolve sir? i am also getting same Failed to create image decoder with message 'unimplemented' error plz help

**Comment by CharryC** [comment] 2021-10-14 06:58
How did you resolve sir?   why closed?
