### ISSUE TITLE
Picasso.get().cancelTag() not stopping loading using Picasso .fetch() 

### ISSUE THREAD

**Issue by almaz010891** [square/picasso#1900] opened 2018-05-16 21:59 UTC
Hi! 
I have a Service, which download a list of images using Picasso.fetch()

```
for (int i = 0; i < imageUrls.size(); i++) {
            String url = imageUrls.get(i);
            Picasso.get()
                    .load(url)
                    .tag(DownloadImagesService.class)
                    .fetch(new Callback(){
});
}
```

imageUrls.size() can be > 2000 items

I starting load and when i called                                 `Picasso.get().cancelTag(DownloadImagesService.class);` onSuccess() callback continues to work for further images.

How I can stop current and future images load?

**Comment by almaz010891** [comment] 2018-05-20 18:11
This same question is on Stackoverflow from another developer:
https://stackoverflow.com/questions/46750598/how-to-cancel-picasso-fetch-requests-by-tag

**Comment by JakeWharton** [comment] 2018-05-20 19:17
Dupe of #1205, as you noted.

**Closed by JakeWharton** 2018-05-20 19:17 UTC
