### ISSUE TITLE
NoSuchElementException in cancelTag

### ISSUE THREAD

**Issue by mblcdr** [square/picasso#1244] opened 2015-12-26 10:59 UTC
I am receiving some exceptions like this:

```Java
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.example.app/com.example.app.activity.PhotoActivity}: java.util.NoSuchElementException
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3285)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3303)
       at android.app.ActivityThread.access$1200(ActivityThread.java:136)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1254)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4800)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.util.NoSuchElementException
       at java.util.WeakHashMap$HashIterator.next(WeakHashMap.java:163)
       at java.util.AbstractCollection.toArray(AbstractCollection.java:343)
       at java.util.ArrayList.(ArrayList.java)
       at com.squareup.picasso.Picasso.cancelTag(Picasso.java:243)
       at com.example.app.activity.PhotoActivity.onDestroy(PhotoActivity.java:176)
       at android.app.Activity.performDestroy(Activity.java:5172)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1109)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3272)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3303)
       at android.app.ActivityThread.access$1200(ActivityThread.java:136)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1254)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4800)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Some of the devices on which the exception occurred:
Samsung GT-I9105, GT-I9190, Sony C2105

Android Versions: 4.0.4, 4.1.2, 4.2.2.

My guess is that this issue is happening because of the custom firmware/ROM that is installed on those devices. However I felt like opening this issue to be sure, and also for reference if someone else experienced something similar.

**Comment by JakeWharton** [comment] 2016-01-05 22:22
This is a dupe of #919 and it's a platform bug, yes.

**Closed by JakeWharton** 2016-01-05 22:22 UTC
