### ISSUE TITLE
Picasso, Kotlin, Jetifier and Windows 10

### ISSUE THREAD

**Issue by nikanorov** [square/picasso#1907] opened 2018-05-29 18:19 UTC
Hello! 

I have faced with the really strange issue related to Picasso, Kotlin, Jetifier and Windows 10. I usually do all my Android development under OSX, but decided to work today on the Windows 10 desktop. 

When I tried to build my project I received the following error: “Unresolved reference: Picasso”. After few hours of investigation, I found the cause is _"android.enableJetifier=true"_ option in _gradle.properties_. I have no idea why this happens, especially only on Windows 10 (can’t reproduce this on my mac). 
This issue happens only in Kotlin files and only on Windows (1803) for me. 

I am not sure this issue is related to Picasso, but this happens only with the latest Picasso version for me. All other libs are ok. 

Steps to reproduce on Windows 10/Android Studio 3.2 Canary 15: 
1) Create test Kotlin project (empty Activity, for exmpl) in Android Studio (my version 3.2-15). 
2) add _implementation 'com.squareup.picasso:picasso:2.71828'_ to gradle and **use Picasso somewhere in the Activity** (Kotlin).
3) Build/run app. Everthing works fine. 
4) Change your compileSdkVersion to "android-P"; 
5) Run "Refactor to AndroidX" option
6) Build/run – “Unresolved reference: Picasso” error. 
7) If you remove “android.enableJetifier=true” from gradle.properties everything builds without any issues. 

My versions: 
Android Studio 3.2 Canary 15
Kotlin plugin: 1.2.41
com.android.tools.build:gradle:3.2.0-alpha15

**Comment by NightlyNexus** [comment] 2018-05-30 17:42
Interesting. Sounds like a Jetifier bug. Maybe see if you can reproduce it without Picasso and just the support annotation library version that it bundles in your project.
b.android.com/new (probably under AndroidX) with a sample project might be the way to go.

**Comment by JakeWharton** [comment] 2018-06-04 18:35
Closing since the whole point of Jetifier is that libraries don't have to do anything to migrate. Please upstream this bug onto http://b.android.com/new

**Closed by JakeWharton** 2018-06-04 18:35 UTC

**Comment by hardysim** [comment] 2018-06-12 06:34
Seems like there's already an issue (with a fix coming up): https://issuetracker.google.com/issues/79642238
