### ISSUE TITLE
Images not loaded on Moto X (2nd gen) with Android 5.1 - displayed black

### ISSUE THREAD

**Issue by awBSH** [square/picasso#1071] opened 2015-06-22 15:15 UTC
Since updating the Moto X (2ng gen) to Android 5.1, images are irregularly not loaded. Instead the image-view is displayed black. This is not reproducible and happens every now and then on different images. It happens for images loaded by URL as well as loaded by resource-ID. 
The problem could temporarily be solve by replacing picasso with a different library (glide).

**Comment by JakeWharton** [comment] 2015-06-22 15:25
There is no information here to make this bug report actionable. Without information such as sample images, example code, or logs of the failures we can't do anything. We cannot just guess what's happening here. If you can gather enough information that we can work with we'll re-open, but closing for now.

**Closed by JakeWharton** 2015-06-22 15:25 UTC

**Comment by awBSH** [comment] 2015-06-22 15:35
Ok, understood. We will have to setup a sample-project to reproduce this problem and provide it here.
So until now, the only information is:
Device: Moto X (2ng gen)
Android: 5.1
Picasso: 2.5.2

Maybe anyone else has experienced the same problem based on that little information?

**Comment by President-Evil** [comment] 2015-07-07 09:33
@JakeWharton @awBSH I've also come across this under the same conditions: Moto X (2nd Gen) using Picasso 2.5.2, and only after installing Android 5.1. I've reproduced it on a smaller basis, using the following:

```Java
public class TestActivity extends AppCompatActivity {
    @InjectView(R.id.a)
    ImageView a;
    @InjectView(R.id.b)
    ImageView b;
    @InjectView(R.id.c)
    ImageView c;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test);
        ButterKnife.inject(this);

        Picasso picasso = Picasso.with(this);
        picasso.setLoggingEnabled(true);
        picasso.load(R.drawable.a).into(a);
        picasso.load(R.drawable.b).into(b);
        picasso.load(R.drawable.c).into(c);
    }
}
```

With `test.xml`:
```xml
<LinearLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:orientation="vertical">

  <ImageView
    android:id="@+id/a"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"/>

  <ImageView
    android:id="@+id/b"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"/>

  <ImageView
    android:id="@+id/c"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"/>

</LinearLayout>
```

Each image `a.png`, `b.png` and `c.png` is a 700x300 entirely white image. The Picasso logs were:
```
07-07 10:13:48.039  21139-21139/? D/Picasso﹕ Main        created      [R0] Request{2130837504}
07-07 10:13:48.041  21139-21139/? D/Picasso﹕ Main        created      [R1] Request{2130837564}
07-07 10:13:48.041  21139-21139/? D/Picasso﹕ Main        created      [R2] Request{2130837565}
07-07 10:13:48.042  21139-21177/? D/Picasso﹕ Dispatcher  enqueued     [R0]+3ms
07-07 10:13:48.042  21139-21177/? D/Picasso﹕ Dispatcher  enqueued     [R1]+1ms
07-07 10:13:48.053  21139-21177/? D/Picasso﹕ Dispatcher  enqueued     [R2]+12ms
07-07 10:13:48.062  21139-21184/? D/Picasso﹕ Hunter      executing    [R0]+18ms
07-07 10:13:48.063  21139-21185/? D/Picasso﹕ Hunter      executing    [R1]+21ms
07-07 10:13:48.067  21139-21187/? D/Picasso﹕ Hunter      executing    [R2]+26ms
07-07 10:13:48.082  21139-21184/? D/Picasso﹕ Hunter      decoded      [R0]+43ms
07-07 10:13:48.082  21139-21187/? D/Picasso﹕ Hunter      decoded      [R2]+41ms
07-07 10:13:48.083  21139-21177/? D/Picasso﹕ Dispatcher  batched      [R2]+42ms for completion
07-07 10:13:48.083  21139-21177/? D/Picasso﹕ Dispatcher  batched      [R0]+44ms for completion
07-07 10:13:48.091  21139-21185/? D/Picasso﹕ Hunter      decoded      [R1]+50ms
07-07 10:13:48.091  21139-21177/? D/Picasso﹕ Dispatcher  batched      [R1]+50ms for completion
07-07 10:13:48.285  21139-21177/? D/Picasso﹕ Dispatcher  delivered    [R2]+243ms, [R0]+245ms, [R1]+243ms
07-07 10:13:48.311  21139-21139/? D/Picasso﹕ Main        completed    [R2]+269ms from DISK
07-07 10:13:48.311  21139-21139/? D/Picasso﹕ Main        completed    [R0]+272ms from DISK
07-07 10:13:48.311  21139-21139/? D/Picasso﹕ Main        completed    [R1]+270ms from DISK
```


**Some observations**
* This is 100% reproducible when the images are different files. I couldn't reproduce it when they were all the same file. However, when using a-b-b (rather than a-b-c) for the drawables, either `a` failed, or both `b`s failed.
* Some other image sizes I tried didn't reproduce the issue: 100x100, 300x300, 400x300. Unfortunately I don't have time to find where the cut-off is.
* Using just two `ImageView`s also reproduces the issue 100% - I've not yet seen a case where all the images load correctly (in my original app or this test case). Equally, I've never seen a case where none of the images load correctly.
* The same behaviour is observed when using `findViewById` rather than ButterKnife.

**Comment by awBSH** [comment] 2015-07-15 16:34
@President-Evil: Thank you for the demo code!
@JakeWharton: Can you please re-open this issue for further analysis?

**Comment by Chirag27592** [comment] 2015-10-14 09:55
i am also facing same problem in Moto x(1st gen) lolipop 5.1.1 .

black images in list view some of elements and others are fine. reInstalling app causes others black .this happens when getting images from asset.
![screenshot_2015-10-14-15-16-42](https://cloud.githubusercontent.com/assets/7995220/10480444/da321ebc-7287-11e5-8c01-5628d562a2b4.png)

**Comment by Chirag27592** [comment] 2015-10-14 10:11
Picasso.with(activity).load(itemName.getItemPath())
				.resize(Utils.w, Utils.pxFromDp(activity, heightInDp))
				.into(holder.image);

In my case Problem occurs when use resize . further cases are resize width and height is 200. when width and height putted 500 then it works perfectly.
