### ISSUE TITLE
Exception: java.io.IOException: Cannot reset

### ISSUE THREAD

**Issue by madmed** [square/picasso#364] opened 2014-01-20 23:06 UTC
Hi Square team!

We are having an issue in an app, when in a listview, images on some rows load but some of them are blank. I tried to trace it and collect as much information as I can.

#### Exception
```java
Picasso:Error:ImageLoadFailed:Uri http://store.indemand.com/shared/ovs/prodimages/movies/t/troublewiththecurve_ID0360906/troublewiththecurveBM_ID0360906.jpg

Picasso:Error:ImageLoadFailed:Exception java.io.IOException: Cannot reset

Picasso:Error:ImageLoadFailed:StackTrace 
[
	com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:94), 
	com.squareup.picasso.NetworkBitmapHunter.decodeStream(NetworkBitmapHunter.java:91), 
	com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:60), 
	com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:111), 
	com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:82), 
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390),
	java.util.concurrent.FutureTask.run(FutureTask.java:234), 
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080), 
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573), 
	java.lang.Thread.run(Thread.java:856), 
	com.squareup.picasso.Utils$PicassoThread.run(Utils.java:218)
]
```
#### Responsible code (under getView())

```java
pBuilder.build().load(URL).fit().into(ImageView);
```

By the way, I don't know if it matters but airplane mode is on, but wifi is connected. I added this because with every row loading, I am seeing this in logs:
```java
W/Settings(4289): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
```

Also the app crashed with this, after scrolling through the list up and down many times;
```java
A/Looper(4289): Could not create wake pipe.  errno=24
A/libc(4289): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 5091 (Picasso-Dispatc)
A/libc(4289): Unable to open connection to debuggerd: Too many open files
```

The app doesn't seem to crash and I also didn't see the W/Settings airplane message if I switch to 				
```java
Picasso.with(_context).load(URL).fit().into(imageView);
``` 
style instead of Picasso.Builder.

**Comment by dnkoutso** [comment] 2015-02-12 16:54
Known issue and number 1 priority for 2.5.1. No more `MarkableInputStream` problems.

**Comment by jacobtabak** [comment] 2015-02-20 21:51
@dnkoutso Is there a workaround for this I could use on a fork?  Also I'm trying to get some more context on the issue - you kind of commented out of the blue that it's a known issue.  Is there more discussion elsewhere?  

We're experiencing this problem specifically on Moto G (2nd gen) loading a full-resolution capture from the camera.

**Comment by dnkoutso** [comment] 2015-02-20 22:18
@jacobtabak have you tried increasing the MARKER constant in `NetworkRequestHandler`? I think the constant was removed but the problem is sometimes Picasso is trying to find the dimensions of the bitmap so it doesnt decode all of it.

If you increase it it will work. We will be working on this to fix it once and for all.

**Comment by jacobtabak** [comment] 2015-02-20 23:29
Thanks @dnkoutso, 

We're loading from disk in this case, and have narrowed it down to something that changed between 2.4 and 2.5.  

By just reverting Picasso 2.4 (and by extension re-adding the okhttp-urlconnection dependency) the issue was resolved.

Unfortunately it's only happening on one device that I don't own (Moto X 2nd gen) so I can't really narrow down the exact change that broke it.

**Comment by sbakhtiarov** [comment] 2015-03-11 10:15
Just fixed a similar issue in my app. Same conditions: Lollipop, ListView and Picasso for loading images  in the list items. On list scroll I occasionally got SEGSEGV. And it worked on the ICS device without any issues.

Problem was in this code for setting up list item:
```
if (some_condition) {
    picasso.load(url).into(imageView);
} else {
    imageView.setImageResource(placeholderResId);
}
```

Solved with using picasso in both cases.

**Comment by tambeti** [comment] 2015-04-27 07:03
As a work around, I wrote a small patch to allow to provide original image dimensions, so if you do have these, the problematic code path could be avoided.

https://github.com/litl/picasso/pull/1/files

**Comment by keekerdc** [comment] 2015-04-27 14:28
Also experiencing this on latest Picasso version just on Moto X 2 (API 21).
Reverting to 2.4 as @jacobtabak mentioned above resolved the issue (thanks)!

**Comment by wenxiang20130910** [comment] 2015-05-11 08:15
I have a problem ,  how to  increase the MARKER size ?I had a big network bitmap for size (4608x3072) can not load !

**Comment by nemanja-kovacevic** [comment] 2015-05-25 03:56
Same here, 2.5.2, Moto X 2nd gen, all is well on other devices I have...

**Comment by bagintz** [comment] 2015-05-27 13:23
I am also having this issue in 2.5.2, Moto G 1st gen

**Comment by mroczis** [comment] 2015-06-10 22:53
Hey,
I'm not sure if I may help you but I'm also facing this problem. This exception is sometimes present no matter how image resolution is big. Lately I was trying to load a 360x360 file from the internet without any success.
One of the images I can't load is located here - http://dotekomanie.cz/wp-content/uploads/2015/04/HTC-One-M8s_PerLeft_GunMetal-360x360.jpg

```java
W/System.err﹕ java.io.IOException: Cannot reset
W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

Nexus 5, Android M + Android 5.1.1, Picasso 2.5.2

**Comment by dnkoutso** [comment] 2015-06-10 23:02
Known issue and tracked for next version. One day. Apologies for this delay.

**Comment by skhaz** [comment] 2015-06-19 20:14
Same issue on Moto E with Android 4.4.4 while loading image from disk.

**Comment by BaronZ** [comment] 2015-07-24 05:57
v 2.5.2 still have this issue while loading local image @dnkoutso  @JakeWharton 
if i dont use resize, i got OOM

**Comment by BaronZ** [comment] 2015-07-24 07:11
works fine using v 2.4.0

**Comment by chrjsorg** [comment] 2015-07-24 19:08
Can confirm. Works fine with v2.4.0.
2.5.2 gave me the same error

    picassoInstance.load(uri).fit().into(imageView);
    uri = file:///storage/emulated/0/WhatsApp/Media/WhatsApp%20Images/IMG-20150724-WA0009.jpeg

**Comment by jeronimo75** [comment] 2015-08-11 17:23
Alas, the last fix is not fixing anything.
I have got in the BitMapHunter.java:
   long mark = markStream.savePosition(65536); // TODO fix this crap.
However I have a call line 140:
   markStream.reset(mark);
and within the markStream the offset=66562
Therefore the reset is failing with the infamous IOException "cannot reset".

I attach the faulting image in case it helps your debugging. I have lollipop.

![63_2hodchmmj_43927](https://cloud.githubusercontent.com/assets/1963460/9204584/5c2b1e7a-405e-11e5-8ac2-3d95376b16b9.jpg)

**Comment by illarionov** [comment] 2015-08-16 12:31
The default MARKER size of 65536 bytes is not enough for a JPEG file having an 65534 bytes EXIF header.

The value of 65536+2048 works better in this case.

**Comment by capezzbr** [comment] 2015-08-28 18:30
Any update on this issue?

**Comment by eygraber** [comment] 2015-08-28 18:32
+1 I'm seeing this when loading images taken by a Droid Turbo 5.1 using 2.5.2

**Comment by Jaymassena** [comment] 2015-08-28 20:39
I'm trying to guage whether I should fork and try some of the work-arounds floating on different issue threads or sit tight till 2.5.3. Any broad guidance on when 2.5.3 might be released?

**Comment by eygraber** [comment] 2015-08-28 20:45
[They don't do ETAs] (https://github.com/square/picasso/issues/364#issuecomment-135882916)

**Comment by Jaymassena** [comment] 2015-08-28 20:47
Sigh...

**Comment by zty5678** [comment] 2015-09-17 05:46
It seems that UIL was using MarkableInputStream before and UIL uses a ContentLengthInputStream now.
See https://github.com/nostra13/Android-Universal-Image-Loader/commit/4f3172262de460ad4b59d86f036c8a38aec9ee93   and  https://github.com/nostra13/Android-Universal-Image-Loader/tree/master/library/src/main/java/com/nostra13/universalimageloader/core/assist

**Comment by sathvik87** [comment] 2015-10-05 12:19
+1 Having same issue on Moto E, using 2.5.2

**Comment by feitengbing2014** [comment] 2015-10-13 09:05
have same issue on huawei p8, 2.5.2

**Comment by jaredrummler** [comment] 2015-10-27 23:11
Same issue on Moto X Style. Picasso 2.5.2. Android 5.1.1.

**Comment by EvilsoulM** [comment] 2015-10-29 07:28
have same issue on oppo R7.Picasso 2.5.2 android 5.1.1. Loading from disk

**Comment by anilshar** [comment] 2015-11-10 17:59
Please fix this issue, I wrote a good amount of code for my app and later struck with this issue. I have to now move to Glide.

**Comment by JakeWharton** [comment] 2015-11-10 17:59
Pull requests are welcome.

**Comment by vedant1811** [comment] 2015-12-02 08:29
Is there a work around for this? Occurring on some devices only (like old Moto G- android 4.4.4)

**Comment by JohnWowUs** [comment] 2015-12-03 10:23
PR #1035 and PR #1219 have been proposed to fix this. One of this may be merged soon or you can roll your own.

**Comment by vedant1811** [comment] 2015-12-03 10:26
@JohnWowUs I'll wait :+1:

**Comment by ubuntudroid** [comment] 2016-01-07 11:37
What's the status here? Eagerly waiting to update our app to the latest version, but this issue keeps us from doing so. PR #1035 looks good.

**Comment by lukaspili** [comment] 2016-01-14 01:55
Experiencing this issue with several images as well: Android 6 + 2.5.2.

**Comment by bbade** [comment] 2016-01-29 20:04
Also happening on my Moto G 3rd gen running M

**Closed** 2016-01-30 02:39 UTC

**Comment by zewenwang** [comment] 2016-03-01 09:51
also happened on Android 5.0.2 with version 2.5.2.
when the modification will be added, and when the version 2.5.3 will be tagged

**Comment by dbacinski** [comment] 2016-03-07 21:20
Same problem on Moto G(6.0) with Picasso version 2.5.2, but it works well with 2.6.0-SNAPSHOT. Picasso release is needed.

**Comment by lisandrop** [comment] 2016-04-21 13:32
This issue is well over 2 years old. Is Picasso still actively maintained? Latest commit is from 2 months ago.

**Comment by cbruegg** [comment] 2016-04-22 10:08
@lisandrop Here's @JakeWharton's explanation from about a month ago: https://www.reddit.com/r/androiddev/comments/4bgaci/autovalue_extensions_jake_wharton/d195t4r

Does Picasso perhaps have a regular contributor outside of Square who could be given the rights to publish updates? Just an idea.

**Comment by dimsuz** [comment] 2016-04-25 22:00
Yeah, it's kinda sad to see this library stagnating a bit. I use it almost in all of my projects...
It's almost perfect, if not for these several bugs like this which are standing out - would be great to have at least one release with them fixed - and I'd say it can stagnate a bit more then ;)

**Comment by JakeWharton** [comment] 2016-04-25 22:00
It'll happen eventually.

**Comment by Maragues** [comment] 2016-07-18 07:40
Upgrading to 2.5.3-SNAPSHOT fixes the issue. Thanks!

**Comment by martygeek** [comment] 2016-10-28 18:01
I just upgraded to 2.5.3-SNAPSHOT as well.  Fixed!

**Comment by lawloretienne** [comment] 2017-01-09 22:15
If there is already a snapshot for 2.5.3 then does that mean v2.5.3 is coming in a few months from now?

**Comment by JakeWharton** [comment] 2017-01-09 22:18
3.0.0 is next

**Comment by ghuiii** [comment] 2017-09-01 07:38
@martygeek @Maragues cannot found 2.5.3-SNAPSHOT , @JakeWharton When will the 3.0.0 come out?

**Comment by getsnoopy** [comment] 2017-10-26 07:23
Could someone publish whatever code is in 2.5.3-SNAPSHOT as a release version please?

**Comment by auf1r2** [comment] 2018-02-15 18:27
Actually wasn't fixed, still happening on 2.5.3-SNAPSHOT
`
...
       at com.squareup.picasso.TargetAction.error(TargetAction.java:49)
       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:581)
       at com.squareup.picasso.Picasso.complete(Picasso.java:528)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:117)`
Unable to load Camera image from internal storage. 
Picasso deliverAction(...) returns null Bitmap.

**Comment by JakeWharton** [comment] 2018-02-15 18:28
The next version is 3.0.0-SNAPSHOT, not 2.5.3-SNAPSHOT.

**Comment by vianairan** [comment] 2018-02-15 21:11
@JakeWharton gradle cannot locate the lib: compile 'com.squareup.picasso:picasso:3.0.0-SNAPSHOT' 

Any suggestions? Thanks a lot

**Comment by JakeWharton** [comment] 2018-02-15 21:13
See the README for the maven repository you must use.

**Comment by vianairan** [comment] 2018-02-16 18:41
Thank you

**Comment by CoolMind** [comment] 2018-02-26 08:57
Thank you! When receiving an image from camera and resizing it with:

`Bitmap bitmap = Picasso.get().load(uri).resize(1000, 0).get();`

got this exception. Upgraded to 3.0.0-SNAPSHOT (See https://github.com/square/picasso/issues/1739). Also change `Picasso.with(context)` to `Picasso.get()`.

**Comment by yayaa** [comment] 2018-12-28 09:34
Looking at the date of comments - @JakeWharton does `2.71828` version contains this fix?

**Comment by dima-doordash** [comment] 2019-02-01 00:51
+1 to the comment from @yayaa . @JakeWharton does `2.71828` includes the fix?

**Comment by paramrana78** [comment] 2020-05-22 05:38
**Same problem**

java.io.IOException: Cannot reset
        at com.squareup.picasso.MarkableInputStream.reset
and yes Upgrading to 2.5.3-SNAPSHOT fixes the issue. 

Thanks!
