### ISSUE TITLE
Image redirection URL can't be loaded

### ISSUE THREAD

**Issue by hegazy** [square/picasso#1428] opened 2016-06-24 17:09 UTC
I'm trying to load this [URL](https://googledrive.com/host/0B-kcmHYQY_ThQ2dxaHdubHN1RHc/Jameos piscina 04.jpg), but it doesn't got loaded. It redirects to another URL. I tried many things but it seems that there is a bug in the bitmap decoder. 

```
skia  --- SkImageDecoder::Factory returned null
--- SkImageDecoder::Factory returned null
--- SkImageDecoder::Factory returned null
--- SkImageDecoder::Factory returned null
```

and when I hook a listener, this is the Exception reported

```
onImageLoadFailed
java.io.IOException: Failed to decode stream.
    at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by JakeWharton** [comment] 2016-06-24 17:13
Dupe of #1191. You can use OkHttp as your Picasso HTTP client which follow redirects automatically (like any sane client should).

**Closed by JakeWharton** 2016-06-24 17:13 UTC

**Comment by hegazy** [comment] 2016-06-24 18:32
@JakeWharton Sorry, I think it's not a redirection issue as I got this loading alright
[http://googledrive.com/host/0B5VEBzUDchotQkVHWll1aEkzOU0/Jameos audiotorio detalle 04.jpg](http://googledrive.com/host/0B5VEBzUDchotQkVHWll1aEkzOU0/Jameos audiotorio detalle 04.jpg)
It's the same service.

**Comment by JakeWharton** [comment] 2016-06-24 18:34
If it's not a redirection issue then it likely doesn't involve Picasso. We have basically 0 control over image decoding. All we do is give Android the bytes and ask it to give us a Bitmap back. When it fails we have no indication as to what's wrong since it all happens deep inside of Android's native code.

**Comment by hegazy** [comment] 2016-06-24 18:48
@JakeWharton Thanks a lot. I've updated my comment above if you can take a look as this doesn't usually happen, it can be a hidden bug. Is this related [android-skimagedecoder-factory-returned-null](http://stackoverflow.com/questions/12006785/android-skimagedecoder-factory-returned-null). I'll dump this URL as a last resort. Thanks :+1: (big fan)

**Comment by JakeWharton** [comment] 2016-06-29 19:37
I don't know what information you added, but the failure to decode is coming from Android. Picasso it just relaying that information as an exception so that the image isn't retried.
