### ISSUE TITLE
PicassoProvider.context is sometimes null

### ISSUE THREAD

**Issue by yanchenko** [square/picasso#1862] opened 2018-04-02 16:06 UTC
After updating to 2.71828 started getting crashes:
```
Caused by: java.lang.IllegalStateException: 
  at com.squareup.picasso.Picasso.get (Picasso.java:681)
```

**Comment by JakeWharton** [comment] 2018-04-02 16:07
With what stacktrace?

**Comment by yanchenko** [comment] 2018-04-02 16:12
That's from the Play Console, I'm yet to reproduce it myself:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2984)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3045)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1642)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386)
Caused by: java.lang.IllegalStateException: 
  at com.squareup.picasso.Picasso.get (Picasso.java:681)
  at my.app.service.PlaybackHandlerService.<init> (PlaybackHandlerService.kt:55)
  at my.app.main.ServiceRegistry$playbackHandlerService$2.invoke (ServiceRegistry.kt:38)
  at my.app.main.ServiceRegistry$playbackHandlerService$2.invoke (ServiceRegistry.kt:29)
  at kotlin.SynchronizedLazyImpl.getValue (Lazy.kt:131)
  at my.app.main.ServiceRegistry.getPlaybackHandlerService (ServiceRegistry.kt)
  at my.app.main.ServiceRegistry.access$getPlaybackHandlerService$p (ServiceRegistry.kt:29)
  at my.app.main.ServiceRegistry$allServices$2.invoke (ServiceRegistry.kt:77)
  at my.app.main.ServiceRegistry$allServices$2.invoke (ServiceRegistry.kt:29)
  at kotlin.SynchronizedLazyImpl.getValue (Lazy.kt:131)
  at my.app.main.ServiceRegistry.getAllServices (ServiceRegistry.kt)
  at my.app.main.ServiceRegistry.<init> (ServiceRegistry.kt:99)
  at my.app.main.ServiceRegistry.<init> (ServiceRegistry.kt:29)
  at my.app.main.ServiceRegistry$Companion.instance (ServiceRegistry.kt:116)
  at my.app.MainActivity.onCreate (MainActivity.kt:29)
  at android.app.Activity.performCreate (Activity.java:6955)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2927)
```

**Comment by JakeWharton** [comment] 2018-04-02 16:53
Hmm that's super weird because at that point the provider should have been able to attach the context. Is there anything interesting about the devices on which the crash occurs?

**Comment by yanchenko** [comment] 2018-04-03 08:12
Samsung phones including S6 & S7, Huawei, ASUS, all running Android 7.0.

**Comment by JakeWharton** [comment] 2018-04-03 19:12
I can't reproduce this on 7.0 myself.

An easy way to ensure this never happens is to create your own `Picasso` instance in `Application.onCreate` and then set it as the singleton instance with `Picasso.setSingletonInstance` in that method.

**Comment by jrodbx** [comment] 2018-04-07 20:13
@yanchenko do any of the components in your application run in a separate process?

**Comment by SimonVT** [comment] 2018-04-07 20:47
There's a bug in N where the backup feature leaves the process in an unusable state. Android then re-uses the unusable process. Basically what happens is that neither your Application subclass or ContentProviders are created in that process, so none of the initialization happens.

**Comment by SimonVT** [comment] 2018-04-07 21:36
I'm not sure, it doesn't happen enough for me to disable backups completely.
If you go that route you should only disable it on <O.

**Comment by harshvishu** [comment] 2018-04-09 06:42
Having the same issue on 
### Motorola G5S plus
### Android 7.1.1

Fixed in Application class using:
`
Picasso.setSingletonInstance(new Picasso.Builder(this).build());
`

**Comment by jrodbx** [comment] 2018-05-16 07:49
No action to take.  Closing.

**Closed by jrodbx** 2018-05-16 07:49 UTC

**Comment by iman2420** [comment] 2019-08-12 09:57
after create `PicassoContentProvider.java`, try to use:

```
<provider
            android:name=".provider.PicassoContentProvider"
            android:authorities="${applicationId}.provider.PicassoContentProvider"
            android:exported="false"/>
```

in **Manifest.xml**.
