### ISSUE TITLE
about cache

### ISSUE THREAD

**Issue by BelongsH** [square/picasso#1367] opened 2016-04-21 03:22 UTC
I have a problem.
when picasso load url(have params),memory cache is not working. but in normal url everything is Ok.

.image.png?version=1.1

``` java
okhttpClient:

client = new OkHttpClient.Builder()
                            .retryOnConnectionFailure(true)
                            .connectTimeout(15, TimeUnit.SECONDS)
                            .cache(new Cache(new File(Environment.getExternalStorageDirectory().getPath() +"image"), 50))
                            .build();

Application:
 int maxMemory = (int) (Runtime.getRuntime().maxMemory() / 4);
        Picasso picasso = new Picasso.Builder(getApplicationContext())
                .memoryCache(new LruCache(maxMemory))
                .downloader(new OkHttp3Downloader(OkHttpUtils.getClient()))
                .build();
        Picasso.setSingletonInstance(picasso);

```

**Comment by JakeWharton** [comment] 2018-03-03 02:46
I cannot reproduce this with the sample. If you can create a sample that reproduces we can take a look. Closing based on the time it's been since the original issue.

**Closed by JakeWharton** 2018-03-03 02:46 UTC
