### ISSUE TITLE
Fail to load a huge image file

### ISSUE THREAD

**Issue by TacticalTwerking** [square/picasso#1059] opened 2015-06-05 06:07 UTC
I am try to load a image file which with a huge size (2432 \* 4320) in to a ImageView 
Before i set the "hardwareAccelerated" as false, you know ,fail
Now i  try to do the same, but if i use resize()  method, it go fail again, so how can i deal with it...thanks

JAVA CODE:
File file = new File("/storage/emulated/0/Pictures/.../IMG_20150605_133117_1035594598.png");

/*\* Work fine */
Picasso.with(getApplicationContext()).load(file).error(R.drawable.ic_launcher).into(mImageView);

/*\* Display error placeholder*/
Picasso.with(getApplicationContext()).load(file).error(R.drawable.ic_launcher).resize(100,100).into(mImageView);

![img_20150605_133117_1035594598](https://cloud.githubusercontent.com/assets/3970859/8000353/15d39daa-0b8c-11e5-8418-aed8e6ca4ada.png)

**Comment by TacticalTwerking** [comment] 2015-06-05 06:18
Sorry ,i don't know if it's a bug or not,  but my gallery app display that successfully
And my device is Moto X gen1 (1280 720), With Cyanogenmod 12.1

**Comment by JohnWowUs** [comment] 2015-06-05 16:53
Without a stack trace it's a bit hard to tell why it isn't working. I suspect it's a "marker" issue. See issue #364.

**Comment by TacticalTwerking** [comment] 2015-06-06 07:19
![20150606150645](https://cloud.githubusercontent.com/assets/3970859/8018780/5aa35320-0c5f-11e5-8ac2-c43a2fa36ad2.png)

Sure mate, so ...i run again, and this is it

**Comment by caiboyi** [comment] 2016-04-08 05:45
https://github.com/square/picasso/issues/907
use picasso 2.4  ，you can load img file and  view it

**Comment by JakeWharton** [comment] 2018-03-03 02:05
Dupe of #754

**Closed by JakeWharton** 2018-03-03 02:05 UTC
