### ISSUE TITLE
picasso2.5.2不能加载魅蓝2的DICM下的图片

### ISSUE THREAD

**Issue by lyx32** [square/picasso#1246] opened 2015-12-28 14:17 UTC
picasso2.5.2不能加载魅蓝2的DICM下的图片，但是用BitmapFactory.decodeFile(pathName)却可以加载

picasso2.5.2 Some phones cannot load the file under DCIM。but using BitmapFactory.decodeFile (pathName) is success

My English is not good, I hope you can understand

**Comment by luffyjet** [comment] 2015-12-29 08:42
嗯 不光是魅蓝2 , mx5 也是。 
some phones made by meizu  may  has this issue。

**Comment by lyx32** [comment] 2015-12-29 13:47
唉。。。。

**Comment by luffyjet** [comment] 2015-12-29 16:16
a same issue :  https://github.com/square/picasso/issues/364

**Comment by luffyjet** [comment] 2015-12-29 16:26
just reverting Picasso 2.4  the issue was resolved.

**Comment by a1154043439** [comment] 2016-01-02 11:41
MX4 has same issue when the image's size is too big

**Comment by luffyjet** [comment] 2016-01-02 11:50
they  will  fix it on 2.5.3.

**Comment by lyx32** [comment] 2016-01-05 07:41
@a1154043439 The problem is not the size of the picture, I also tried to download a> 5M picture, the same can be a normal load, but it is not out of the picture camera
话说为嘛没人说中文？

**Comment by lyx32** [comment] 2016-01-05 07:41
只能期待2.5.3咯。

**Comment by l419070777** [comment] 2016-01-05 07:43
这个错误有人遇到过没 
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
       at android.content.res.Resources.loadDrawable(Resources.java:2110)
       at android.content.res.Resources.getDrawable(Resources.java:700)
       at com.squareup.picasso.RequestCreator.getPlaceholderDrawable(RequestCreator.java:676)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:664)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)
       at com.bbtree.cardreader.ui.screensaver.adapter.ScreenSaverPagerAdapter.initView(ScreenSaverPagerAdapter.java:107)
       at com.bbtree.cardreader.ui.screensaver.adapter.ScreenSaverPagerAdapter.instantiateItem(ScreenSaverPagerAdapter.java:77)
       at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:870)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
       at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
       at com.bbtree.cardreader.ui.screensaver.ScreenSaverPagerFrg$2.handleMessage(ScreenSaverPagerFrg.java:97)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by l419070777** [comment] 2016-01-05 07:44
加载 placeHolder 时候oom

**Comment by DolphinBoy** [comment] 2016-01-19 02:23
只要调用resize就会加载出错，如果不掉用就会OOM

**Comment by a1154043439** [comment] 2016-01-19 02:44
you can try 2.4.0,use
compile 'com.squareup.picasso:picasso:2.4.0'
instead of
compile 'com.squareup.picasso:picasso:2.5.2'
this work for me.

**Comment by JakeWharton** [comment] 2016-01-26 17:34
Dupe of #364.

**Closed by JakeWharton** 2016-01-26 17:34 UTC

**Comment by zhuojianhai** [comment] 2016-03-09 02:07
Error:A problem occurred configuring project ':ECTECTAndroid'.
> A problem occurred configuring project ':multi-image-selector'.
   > Could not resolve all dependencies for configuration ':multi-image-selector:_debugCompile'.
      > Could not find com.squareup.picasso:picasso:2.4.0.
        Searched in the following locations:
            file:/E:/software/adt-bundle-windows-x86_64-20140702/newsdk/sdk/extras/android/m2repository/com/squareup/picasso/picasso/2.4.0/picasso-2.4.0.pom
            file:/E:/software/adt-bundle-windows-x86_64-20140702/newsdk/sdk/extras/android/m2repository/com/squareup/picasso/picasso/2.4.0/picasso-2.4.0.jar
            file:/E:/software/adt-bundle-windows-x86_64-20140702/newsdk/sdk/extras/google/m2repository/com/squareup/picasso/picasso/2.4.0/picasso-2.4.0.pom
            file:/E:/software/adt-bundle-windows-x86_64-20140702/newsdk/sdk/extras/google/m2repository/com/squareup/picasso/picasso/2.4.0/picasso-2.4.0.jar
        Required by:
            native_studio_last:multi-image-selector:unspecified
