### ISSUE TITLE
3.0.0-SNAPSHOT was broken

### ISSUE THREAD

**Issue by CoolMind** [square/picasso#1753] opened 2018-03-02 07:56 UTC
Hello!
Following to recommendation I updated a library to 3.0.0-SNAPSHOT, and on February, 28 you updated it with **the same version**, even didn't test it. That's very bad.
https://oss.sonatype.org/content/repositories/snapshots/com/squareup/picasso/picasso/3.0.0-SNAPSHOT/
Doesn't work on many devices.
Please, roll back to a previous version and update as 3.0.1-SNAPSHOT. Don't change the same release.
Probably a problem appears for this line:

`Picasso.get().load(uri).resize(1000, 0).get();`

where uri is an image received from Gallery or Camera. After resizing the image is not shown.

**Comment by JakeWharton** [comment] 2018-03-02 13:33
Dupe of #1752. Not an actionable report.

**Closed by JakeWharton** 2018-03-02 13:33 UTC

**Comment by CoolMind** [comment] 2018-03-02 14:00
Jake, really? This is the way you work with issues. Update failed libraries with the same version, don't test, don't understand what people are writing and close issues.
Very bad.

**Comment by JakeWharton** [comment] 2018-03-02 14:15
A snapshot version is the latest, yes. That's working as intended. There
are tests in this project that run automatically. If your use case isn't
covered by it then submit a failing test or a sample that reproduces the
problem reliably to increase the test coverage. I understood exactly what
you wrote on the last issue and commented to it. Perhaps you didn't
understand my reply indicating that your report contained no value
information and was not actionable and that it was likely a duplicate of an
existing issue or you wouldn't have created this one.

**Comment by CoolMind** [comment] 2018-03-02 14:50
Thanks for the answer. I will try to add some tests.
Also Picasso changed OkHTTP.

    public Response build() {
      if (request == null) throw new IllegalStateException("request == null");
      if (protocol == null) throw new IllegalStateException("protocol == null");
      if (code < 0) throw new IllegalStateException("code < 0: " + code);
      if (message == null) throw new IllegalStateException("message == null");
      return new Response(this);
    }

A line with `message` is added leading to exception "java.lang.IllegalStateException: message == null" when launching a test containing

`HttpException exception = new HttpException(Response.error(400, ResponseBody.create(MediaType.parse("application/x-www-form-urlencoded"), "")));`
